### ISSUE TITLE
[UI] Add a message for violated rules 

### ISSUE THREAD

**Issue by SaharMehrpour** [ourcodeinc/ActiveDocumentation-webapp#13]
For "Violated Rules" page:
- Add a tooltip ( add (i) besides "Violated Rules" header ) to describe what this page shows.

![Screenshot 2024-07-05 at 5 06 14 PM](https://github.com/ourcodeinc/ActiveDocumentation-webapp/assets/21271498/a613cf70-5c5c-4f51-bb3a-4e15faafe558)

**Comment by RBP98** [comment]
Hey!
Can you assign this issue to me? I would like to work on this issue.

**Comment by SaharMehrpour** [comment]
Question: Do we want to display a message, when the page is empty?

**Comment by RBP98** [comment]
We already have a message when the page is empty. Do you want me to add anything else to the message?

![image](https://github.com/user-attachments/assets/75f958b6-a463-4ca5-903f-dfd05bee99df)

**Comment by SaharMehrpour** [comment]
I think the current version should be good enough for now. We can open a new issue if we want.
