### ISSUE TITLE
[RulePad] The textual editor and the graphical editor are not synced correctly.

### ISSUE THREAD

**Issue by SaharMehrpour** [ourcodeinc/ActiveDocumentation-webapp#15]
- The textual editor is not updated. In this example the star icon is also placed incorrectly.
<img width="700" alt="Screenshot 2024-07-09 at 1 35 11 PM" src="https://github.com/ourcodeinc/ActiveDocumentation-webapp/assets/21271498/f88f3190-92e6-49a7-be5d-301a9eb96a3b">

- Elements are repeated in the textual editor.
<img width="700" alt="Screenshot 2024-07-09 at 1 38 54 PM" src="https://github.com/ourcodeinc/ActiveDocumentation-webapp/assets/21271498/cf4b650f-c2c4-49f4-8340-c8844dc05e72">
<img width="700" alt="Screenshot 2024-07-09 at 1 33 11 PM" src="https://github.com/ourcodeinc/ActiveDocumentation-webapp/assets/21271498/b26685b9-9259-4f98-8f69-abd9993f9a3e">

**Comment by sanjeev30** [comment]
When we add a rule in the rule pad graphical editor, clicking the check box twice duplicates the rule. It alternates between two rules and one rule of same type.

<img width="1142" alt="Screenshot 2024-08-29 at 1 58 04 PM" src="https://github.com/user-attachments/assets/6175161a-09cb-44eb-be2c-980b31524265">

<img width="1145" alt="Screenshot 2024-08-29 at 1 58 20 PM" src="https://github.com/user-attachments/assets/c5791000-3106-4a07-997d-fef4ab104f3f">
