### ISSUE TITLE
[UI] Disconnection message

### ISSUE THREAD

**Issue by SaharMehrpour** [ourcodeinc/ActiveDocumentation-webapp#2]
Make it generalizable by removing "IntelliJ"

![Screenshot 2024-07-05 at 4 58 47 PM](https://github.com/ourcodeinc/ActiveDocumentation-webapp/assets/21271498/3ff6fb8e-254a-4fd2-a5b6-770e6f400f35)

**Comment by sanjeev30** [comment]
The message in the headerBar.js file can be changed to make a generalized error message.
