### ISSUE TITLE
[UI] Add a welcome message for empty ActiveDocumentation

### ISSUE THREAD

**Issue by SaharMehrpour** [ourcodeinc/ActiveDocumentation-webapp#3]
- Add a message on what to do when facing an empty "Table of Contents".

- *Table of Contents*
![Screenshot 2024-07-05 at 5 06 01 PM](https://github.com/ourcodeinc/ActiveDocumentation-webapp/assets/21271498/15806a82-078c-42c6-9211-769b158f8ae3)

**Comment by nikitha1999** [comment]
What message exactly are you looking at?
