### ISSUE TITLE
[UI] Edit the NavBar to hide arrows and show the logo.

### ISSUE THREAD

**Issue by SaharMehrpour** [ourcodeinc/ActiveDocumentation-webapp#30]
The arrows should be hidden, but the functionality should be kept.
The logo of OurCode.io can be displayed on the left side of the NavBar.
![Screenshot 2024-09-03 at 3 06 32 PM](https://github.com/user-attachments/assets/b7bfb126-5b42-479e-9530-56cbf57613b6)

When the NavBar is collapsed, the logo should still be visible.
![Screenshot 2024-09-03 at 3 06 40 PM](https://github.com/user-attachments/assets/1b74ab47-ac37-42cd-94ad-481a7dfa61c4)

**Comment by Sky-De** [comment]
@SaharMehrpour hi , i would like to fix this , please assign this to me, thanks

**Comment by Sky-De** [comment]
@SaharMehrpour Hi again, I tried to run your app on my machine. Unfortunately, I didn't read the contribute guide before asking about this issue. Your app requires tremendous effort and time just to get it to run (too many steps), and it is beyond the time I can dedicate to contributing. I hope you understand. I will also unassign myself from this issue.
thanks
skyde

**Comment by pranay-sharma793** [comment]
Hey @SaharMehrpour, I would like to work on this.
