### ISSUE TITLE
[RulePad][UI] The save feature for file/folder selector is not visible for users.

### ISSUE THREAD

**Issue by SaharMehrpour** [ourcodeinc/ActiveDocumentation-webapp#33]
After selecting files / folders, users would not **save** the files/folders.
![file-folder](https://github.com/user-attachments/assets/aa58a0e7-f1fb-45be-8ad3-9f263f9cada6)

Ideas: 
- Move the save icon to the right, immediately after the last dropdown.
- Add a tooltip.
- Add a label for the icon like "Save".

**Comment by samyak1326** [comment]
Can you assign me this issue @SaharMehrpour  ?
