### ISSUE TITLE
[UI][RulePad] the position of the star icon in RulePad causes errors.

### ISSUE THREAD

**Issue by SaharMehrpour** [ourcodeinc/ActiveDocumentation-webapp#38]
When the star icon is not displayed, only the checkbox and the eraser icons are displayed.
![Screenshot 2024-09-18 at 3 42 16 PM](https://github.com/user-attachments/assets/2f2db7d0-14b1-41a6-b856-2fe060fc8ac6)

However, when star icon is displayed, the position of the checkbox and the eraser icons are changed. When there is a delay in clicking the checkbox, this update in location causes the error for users when they want to click on checkbox, but they click on the eraser icon.
![Screenshot 2024-09-18 at 3 42 22 PM](https://github.com/user-attachments/assets/180cf7d0-9ed0-4454-88bd-f071ca4ee1de)

Suggested fix: move the star icon before the other icons to keep the position of the icons.

**Comment by nikitha1999** [comment]
Yeah, I can look into the issue and move the star to the other side rather than the last.
