### ISSUE TITLE
[UI] Add file names to snippets.

### ISSUE THREAD

**Issue by SaharMehrpour** [ourcodeinc/ActiveDocumentation-webapp#5]
Display the path of the file from which the code snippet is extracted, preferably on the right side of the snippet.

<img width="718" alt="Screenshot 2024-07-09 at 12 15 34 PM" src="https://github.com/ourcodeinc/ActiveDocumentation-webapp/assets/21271498/b843290b-5eff-4960-bbde-c53389f85e58">

Snippets are displayed in 3 places:
- RulePanel
- RulePad
- DesignRuleMiner

When ActiveLLM is activated, for violated snippets in RulePanel, another button is displayed:
![fix_button](https://github.com/ourcodeinc/ActiveDocumentation-webapp/assets/21271498/cca13b2d-b5fa-4747-b1ac-65ac4492d68d)

Requirements:
- Font color: Dark gray
- Text alignment: Right
- Font size: Adjusted to fit two lines in the snippet box
- Path characters: Truncated with ellipsis if too long, example: "...long/path/to/file.java"
-- A path is long if when displayed exceeds the minimum of 1/3 of the snippet width or roughly 300px

**Comment by Swathi-Guptha** [comment]
I can take up this issue.
