### ISSUE TITLE
[UI][DesignRuleMiner] Add a button to enable/disable the purple color coding

### ISSUE THREAD

**Issue by SaharMehrpour** [ourcodeinc/ActiveDocumentation-webapp#6]
In DesignRuleMiner page, elements are colored based on their frequency.
https://github.com/ourcodeinc/ActiveDocumentation-webapp/blob/main/src/ui/MiningRules/minedRulePad.js#L275

![dropdowns](https://github.com/ourcodeinc/ActiveDocumentation-webapp/assets/21271498/3145143d-20c0-4cb5-afc8-6f5d9003befe)

Add a setting option on top of the page to enable/disable color coding for frequency.

**Comment by samyak1326** [comment]
Hey, I would like to work on this enhancement.
